customhost = "employee01.c7fd3pe0tdjg.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "12345678"
customdb = "employee01"
custombucket = "zhengmaybucket-employee"
customregion = "us-east-1"
